"""Create Tables

Revision ID: 9edee9f0940f
Revises: b6aec9715b77
Create Date: 2023-09-22 06:24:11.530477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edee9f0940f'
down_revision = 'b6aec9715b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
